INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR001', '2', 'Food arrived slightly cold.', '11-Mar-20', 'O001');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR002', '5', 'Perfect as always!', '22-Apr-20', 'O002');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR003', '2', 'Food arrived slightly cold.', '7-Aug-22', 'O003');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR004', '4', 'Good portion sizes.', '21-Oct-24', 'O004');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR005', '5', 'Perfect as always!', '18-Oct-23', 'O005');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR006', '3', 'Average taste.', '17-Jun-23', 'O006');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR007', '3', 'It was okay.', '4-Dec-21', 'O007');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR008', '3', 'Nothing special, but decent.', '4-Oct-25', 'O008');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR009', '3', 'Nothing special, but decent.', '30-Jan-25', 'O009');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR010', '5', 'Hot, fresh, and on time!', '10-May-25', 'O010');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR011', '1', 'Food was completely ruined.', '30-Jun-25', 'O011');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR012', '1', 'Terrible experience.', '16-Oct-23', 'O012');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR013', '2', 'A bit bland.', '22-Oct-25', 'O013');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR014', '5', 'Hot, fresh, and on time!', '22-Jan-20', 'O014');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR015', '3', 'Nothing special, but decent.', '25-Jun-20', 'O015');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR016', '1', 'Would not order again.', '9-Dec-24', 'O016');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR017', '4', 'Enjoyed the meal.', '4-Aug-20', 'O017');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR018', '1', 'Terrible experience.', '9-Mar-25', 'O018');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR019', '1', 'Would not order again.', '9-May-24', 'O019');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR020', '5', 'Absolutely delicious!', '10-Aug-21', 'O020');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR021', '3', 'Nothing special, but decent.', '6-Jul-25', 'O021');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR022', '5', 'Perfect as always!', '31-Aug-25', 'O023');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR023', '1', 'Terrible experience.', '31-Aug-25', 'O024');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR024', '3', 'It was okay.', '3-Jun-24', 'O025');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR025', '4', 'Enjoyed the meal.', '4-Sep-22', 'O026');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR026', '5', 'Hot, fresh, and on time!', '16-Nov-20', 'O027');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR027', '4', 'Good portion sizes.', '4-Aug-21', 'O028');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR028', '2', 'Not exactly what I expected.', '1-Nov-21', 'O029');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR029', '5', 'Hot, fresh, and on time!', '24-Jun-20', 'O030');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR030', '2', 'Food arrived slightly cold.', '14-Jan-21', 'O031');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR031', '5', 'Absolutely delicious!', '10-Jun-21', 'O032');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR032', '5', 'Perfect as always!', '14-Dec-23', 'O033');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR033', '2', 'Not exactly what I expected.', '7-Feb-20', 'O034');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR034', '2', 'A bit bland.', '16-Nov-25', 'O035');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR035', '3', 'Average taste.', '10-May-21', 'O036');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR036', '2', 'A bit bland.', '18-Sep-25', 'O037');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR037', '5', 'Absolutely delicious!', '28-Apr-21', 'O038');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR038', '4', 'Good portion sizes.', '17-Nov-25', 'O039');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR039', '3', 'It was okay.', '7-Jan-21', 'O040');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR040', '3', 'Nothing special, but decent.', '29-Aug-24', 'O041');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR041', '3', 'Average taste.', '15-Jul-22', 'O042');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR042', '4', 'Good portion sizes.', '1-May-21', 'O043');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR043', '3', 'Nothing special, but decent.', '6-Oct-23', 'O044');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR044', '2', 'A bit bland.', '20-Jan-26', 'O045');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR045', '1', 'Food was completely ruined.', '14-May-24', 'O046');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR046', '1', 'Food was completely ruined.', '28-May-20', 'O047');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR047', '3', 'Nothing special, but decent.', '26-Sep-25', 'O048');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR048', '5', 'Hot, fresh, and on time!', '12-Feb-26', 'O049');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR049', '1', 'Terrible experience.', '10-Jun-21', 'O050');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR050', '5', 'Absolutely delicious!', '23-Nov-24', 'O051');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR051', '5', 'Hot, fresh, and on time!', '13-Jun-20', 'O052');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR052', '1', 'Would not order again.', '14-Nov-21', 'O053');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR053', '3', 'Nothing special, but decent.', '5-Oct-21', 'O054');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR054', '3', 'Nothing special, but decent.', '24-Feb-23', 'O055');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR055', '5', 'Perfect as always!', '30-Mar-22', 'O056');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR056', '4', 'Enjoyed the meal.', '29-Mar-24', 'O057');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR057', '5', 'Absolutely delicious!', '4-Feb-26', 'O058');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR058', '2', 'Not exactly what I expected.', '11-Oct-23', 'O059');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR059', '4', 'Really good food.', '26-Dec-21', 'O060');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR060', '5', 'Absolutely delicious!', '2-Apr-22', 'O061');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR061', '2', 'Food arrived slightly cold.', '23-Aug-25', 'O062');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR062', '5', 'Absolutely delicious!', '1-Jul-20', 'O063');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR063', '2', 'Food arrived slightly cold.', '17-Jan-21', 'O064');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR064', '4', 'Enjoyed the meal.', '6-Dec-24', 'O066');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR065', '1', 'Would not order again.', '11-Apr-23', 'O067');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR066', '2', 'Food arrived slightly cold.', '26-Feb-22', 'O068');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR067', '4', 'Really good food.', '20-Oct-20', 'O069');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR068', '2', 'Food arrived slightly cold.', '1-Sep-25', 'O070');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR069', '1', 'Would not order again.', '22-Aug-25', 'O071');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR070', '4', 'Really good food.', '28-Dec-24', 'O072');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR071', '5', 'Absolutely delicious!', '22-Jul-23', 'O073');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR072', '5', 'Hot, fresh, and on time!', '22-Sep-23', 'O074');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR073', '3', 'Average taste.', '27-Feb-21', 'O075');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR074', '2', 'Not exactly what I expected.', '13-Apr-23', 'O076');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR075', '5', 'Perfect as always!', '6-Oct-20', 'O077');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR076', '5', 'Absolutely delicious!', '24-May-23', 'O078');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR077', '5', 'Absolutely delicious!', '27-Jun-22', 'O079');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR078', '4', 'Good portion sizes.', '16-Feb-26', 'O080');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR079', '2', 'Food arrived slightly cold.', '23-Dec-21', 'O081');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR080', '1', 'Food was completely ruined.', '20-Oct-21', 'O082');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR081', '1', 'Would not order again.', '17-Oct-22', 'O083');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR082', '5', 'Perfect as always!', '12-Sep-21', 'O084');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR083', '3', 'Nothing special, but decent.', '18-Feb-22', 'O085');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR084', '5', 'Perfect as always!', '5-Oct-23', 'O086');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR085', '2', 'Not exactly what I expected.', '1-Jun-20', 'O087');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR086', '3', 'It was okay.', '29-Jan-24', 'O088');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR087', '2', 'Food arrived slightly cold.', '30-Nov-20', 'O089');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR088', '2', 'Food arrived slightly cold.', '5-Apr-20', 'O090');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR089', '2', 'A bit bland.', '18-Mar-21', 'O091');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR090', '5', 'Absolutely delicious!', '24-Jan-21', 'O092');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR091', '5', 'Absolutely delicious!', '23-May-23', 'O093');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR092', '5', 'Perfect as always!', '1-Jul-25', 'O094');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR093', '1', 'Terrible experience.', '2-Jul-24', 'O095');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR094', '1', 'Would not order again.', '24-Apr-21', 'O096');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR095', '3', 'Nothing special, but decent.', '21-Mar-24', 'O097');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR096', '3', 'Average taste.', '7-Jul-24', 'O098');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR097', '2', 'Food arrived slightly cold.', '14-May-24', 'O100');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR098', '2', 'A bit bland.', '22-Mar-20', 'O101');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR099', '1', 'Food was completely ruined.', '20-Dec-23', 'O102');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR100', '2', 'Not exactly what I expected.', '17-Dec-23', 'O103');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR101', '5', 'Perfect as always!', '31-Dec-22', 'O104');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR102', '5', 'Absolutely delicious!', '2-Jul-23', 'O105');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR103', '1', 'Would not order again.', '28-Apr-23', 'O106');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR104', '2', 'Not exactly what I expected.', '12-Jun-22', 'O107');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR105', '3', 'Nothing special, but decent.', '17-May-21', 'O108');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR106', '1', 'Terrible experience.', '3-Mar-24', 'O109');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR107', '2', 'A bit bland.', '9-Sep-20', 'O110');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR108', '1', 'Terrible experience.', '20-Mar-23', 'O111');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR109', '3', 'Average taste.', '24-Nov-21', 'O112');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR110', '3', 'It was okay.', '23-Jan-25', 'O114');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR111', '1', 'Food was completely ruined.', '25-Nov-25', 'O115');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR112', '2', 'Not exactly what I expected.', '1-Jan-22', 'O116');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR113', '5', 'Perfect as always!', '4-May-24', 'O117');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR114', '4', 'Really good food.', '21-Aug-20', 'O118');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR115', '2', 'Not exactly what I expected.', '30-Dec-25', 'O119');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR116', '2', 'Not exactly what I expected.', '6-Jul-21', 'O120');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR117', '1', 'Food was completely ruined.', '22-Dec-24', 'O121');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR118', '2', 'A bit bland.', '5-Mar-25', 'O123');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR119', '3', 'It was okay.', '2-Oct-23', 'O124');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR120', '2', 'Not exactly what I expected.', '16-Jan-20', 'O125');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR121', '2', 'Food arrived slightly cold.', '15-Aug-21', 'O126');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR122', '1', 'Terrible experience.', '23-Dec-25', 'O127');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR123', '3', 'It was okay.', '14-Mar-20', 'O128');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR124', '2', 'Not exactly what I expected.', '18-Oct-25', 'O129');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR125', '5', 'Perfect as always!', '3-Mar-20', 'O130');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR126', '2', 'Not exactly what I expected.', '14-Jun-21', 'O131');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR127', '1', 'Would not order again.', '11-Feb-20', 'O132');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR128', '2', 'Food arrived slightly cold.', '10-Jul-24', 'O133');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR129', '4', 'Really good food.', '18-Sep-20', 'O134');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR130', '3', 'Average taste.', '7-May-20', 'O135');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR131', '2', 'Not exactly what I expected.', '3-Aug-22', 'O136');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR132', '2', 'Food arrived slightly cold.', '12-May-25', 'O137');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR133', '5', 'Perfect as always!', '1-Feb-20', 'O138');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR134', '4', 'Enjoyed the meal.', '15-Nov-20', 'O139');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR135', '2', 'A bit bland.', '15-Jul-20', 'O140');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR136', '3', 'Average taste.', '6-Apr-25', 'O142');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR137', '4', 'Good portion sizes.', '4-Jan-24', 'O143');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR138', '4', 'Really good food.', '14-Jun-20', 'O144');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR139', '4', 'Really good food.', '25-Jul-21', 'O145');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR140', '2', 'Food arrived slightly cold.', '9-Sep-21', 'O146');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR141', '1', 'Food was completely ruined.', '16-Mar-22', 'O147');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR142', '3', 'Average taste.', '21-May-22', 'O148');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR143', '2', 'A bit bland.', '17-Oct-24', 'O149');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR144', '4', 'Enjoyed the meal.', '13-Sep-22', 'O150');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR145', '1', 'Terrible experience.', '22-Jul-20', 'O151');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR146', '2', 'Not exactly what I expected.', '23-Feb-21', 'O152');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR147', '4', 'Enjoyed the meal.', '16-Dec-22', 'O153');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR148', '4', 'Enjoyed the meal.', '25-Dec-24', 'O154');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR149', '5', 'Absolutely delicious!', '3-Apr-23', 'O155');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR150', '2', 'A bit bland.', '13-Jul-23', 'O156');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR151', '2', 'Food arrived slightly cold.', '29-Jul-22', 'O157');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR152', '2', 'Not exactly what I expected.', '6-Nov-20', 'O158');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR153', '1', 'Terrible experience.', '27-Nov-23', 'O159');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR154', '5', 'Absolutely delicious!', '16-Aug-24', 'O160');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR155', '5', 'Perfect as always!', '12-Apr-25', 'O161');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR156', '4', 'Enjoyed the meal.', '6-May-24', 'O162');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR157', '1', 'Food was completely ruined.', '5-Dec-22', 'O163');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR158', '5', 'Absolutely delicious!', '29-Jan-24', 'O164');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR159', '4', 'Really good food.', '9-Feb-24', 'O165');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR160', '5', 'Hot, fresh, and on time!', '16-Apr-24', 'O166');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR161', '2', 'Not exactly what I expected.', '6-Jun-23', 'O167');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR162', '5', 'Hot, fresh, and on time!', '7-Apr-25', 'O168');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR163', '1', 'Would not order again.', '29-Dec-20', 'O169');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR164', '4', 'Enjoyed the meal.', '28-Oct-21', 'O170');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR165', '1', 'Food was completely ruined.', '3-Mar-24', 'O171');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR166', '1', 'Would not order again.', '7-May-24', 'O172');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR167', '4', 'Really good food.', '28-Dec-21', 'O173');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR168', '1', 'Food was completely ruined.', '28-May-24', 'O174');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR169', '2', 'A bit bland.', '14-Sep-24', 'O175');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR170', '4', 'Enjoyed the meal.', '13-Sep-24', 'O176');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR171', '2', 'Not exactly what I expected.', '20-Sep-25', 'O177');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR172', '4', 'Enjoyed the meal.', '30-Apr-20', 'O178');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR173', '2', 'Not exactly what I expected.', '12-Sep-22', 'O179');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR174', '1', 'Terrible experience.', '8-Jan-24', 'O180');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR175', '4', 'Enjoyed the meal.', '9-Nov-23', 'O181');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR176', '4', 'Really good food.', '20-Apr-24', 'O182');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR177', '5', 'Hot, fresh, and on time!', '14-Dec-21', 'O183');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR178', '5', 'Hot, fresh, and on time!', '22-Aug-23', 'O184');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR179', '5', 'Perfect as always!', '22-Jul-21', 'O185');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR180', '5', 'Absolutely delicious!', '9-Jun-21', 'O186');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR181', '1', 'Food was completely ruined.', '17-Dec-25', 'O187');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR182', '3', 'Average taste.', '21-Dec-20', 'O188');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR183', '2', 'Not exactly what I expected.', '21-Apr-25', 'O189');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR184', '3', 'Average taste.', '13-Aug-20', 'O190');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR185', '5', 'Hot, fresh, and on time!', '20-Mar-22', 'O191');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR186', '2', 'A bit bland.', '8-Jan-25', 'O192');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR187', '4', 'Good portion sizes.', '27-Feb-22', 'O193');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR188', '3', 'Nothing special, but decent.', '7-Jun-21', 'O194');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR189', '3', 'Nothing special, but decent.', '5-Oct-22', 'O195');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR190', '4', 'Really good food.', '1-Sep-22', 'O196');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR191', '4', 'Enjoyed the meal.', '3-Jul-21', 'O197');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR192', '1', 'Would not order again.', '13-Jul-25', 'O198');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR193', '5', 'Perfect as always!', '3-Apr-20', 'O199');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR194', '5', 'Absolutely delicious!', '17-Oct-20', 'O200');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR195', '2', 'Food arrived slightly cold.', '2-May-25', 'O201');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR196', '3', 'Average taste.', '7-Apr-20', 'O203');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR197', '5', 'Hot, fresh, and on time!', '3-Jul-25', 'O204');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR198', '2', 'Not exactly what I expected.', '1-Jun-23', 'O206');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR199', '5', 'Hot, fresh, and on time!', '24-Apr-21', 'O207');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR200', '3', 'Average taste.', '14-Oct-22', 'O208');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR201', '4', 'Good portion sizes.', '28-Feb-21', 'O209');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR202', '5', 'Hot, fresh, and on time!', '15-Feb-21', 'O210');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR203', '3', 'It was okay.', '26-Jul-20', 'O211');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR204', '1', 'Terrible experience.', '9-Nov-23', 'O212');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR205', '3', 'Nothing special, but decent.', '18-Jul-21', 'O213');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR206', '1', 'Food was completely ruined.', '8-Jun-22', 'O214');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR207', '3', 'Nothing special, but decent.', '23-Nov-24', 'O215');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR208', '5', 'Perfect as always!', '17-Sep-24', 'O216');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR209', '5', 'Hot, fresh, and on time!', '27-Mar-24', 'O217');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR210', '1', 'Would not order again.', '14-Mar-24', 'O218');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR211', '1', 'Would not order again.', '18-Sep-20', 'O219');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR212', '2', 'Food arrived slightly cold.', '11-Apr-20', 'O221');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR213', '2', 'Food arrived slightly cold.', '15-Aug-20', 'O222');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR214', '3', 'Nothing special, but decent.', '22-Dec-25', 'O223');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR215', '5', 'Hot, fresh, and on time!', '14-Jan-21', 'O224');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR216', '4', 'Good portion sizes.', '22-Dec-22', 'O225');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR217', '1', 'Food was completely ruined.', '3-Dec-24', 'O226');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR218', '5', 'Perfect as always!', '22-Dec-24', 'O227');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR219', '2', 'Not exactly what I expected.', '25-Jul-23', 'O228');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR220', '5', 'Absolutely delicious!', '15-Jul-21', 'O229');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR221', '5', 'Hot, fresh, and on time!', '12-Apr-25', 'O230');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR222', '4', 'Really good food.', '9-Jan-23', 'O231');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR223', '3', 'Average taste.', '9-Jun-24', 'O232');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR224', '2', 'Food arrived slightly cold.', '16-Jan-25', 'O233');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR225', '4', 'Really good food.', '21-May-23', 'O234');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR226', '3', 'Average taste.', '4-Dec-22', 'O235');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR227', '2', 'Food arrived slightly cold.', '27-Jun-23', 'O236');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR228', '5', 'Absolutely delicious!', '29-May-25', 'O237');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR229', '5', 'Absolutely delicious!', '24-Jul-21', 'O238');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR230', '2', 'A bit bland.', '22-Oct-22', 'O239');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR231', '2', 'Not exactly what I expected.', '2-Feb-24', 'O240');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR232', '2', 'Food arrived slightly cold.', '24-Oct-24', 'O241');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR233', '4', 'Enjoyed the meal.', '20-Sep-23', 'O242');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR234', '1', 'Terrible experience.', '24-Mar-22', 'O243');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR235', '4', 'Good portion sizes.', '14-May-20', 'O244');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR236', '2', 'Not exactly what I expected.', '10-Dec-20', 'O245');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR237', '2', 'A bit bland.', '21-Dec-23', 'O246');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR238', '2', 'A bit bland.', '27-Oct-25', 'O247');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR239', '4', 'Good portion sizes.', '21-Nov-21', 'O248');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR240', '4', 'Good portion sizes.', '5-Oct-23', 'O249');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR241', '1', 'Food was completely ruined.', '29-Jul-24', 'O250');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR242', '4', 'Enjoyed the meal.', '1-Nov-25', 'O251');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR243', '5', 'Perfect as always!', '25-Jan-20', 'O252');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR244', '1', 'Terrible experience.', '5-Jan-26', 'O254');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR245', '4', 'Enjoyed the meal.', '6-Nov-22', 'O255');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR246', '5', 'Perfect as always!', '28-Jul-20', 'O257');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR247', '5', 'Perfect as always!', '12-Aug-21', 'O258');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR248', '1', 'Terrible experience.', '10-Mar-23', 'O259');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR249', '4', 'Really good food.', '29-May-21', 'O260');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR250', '1', 'Would not order again.', '3-Jul-25', 'O261');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR251', '4', 'Enjoyed the meal.', '6-Aug-21', 'O262');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR252', '4', 'Really good food.', '18-Mar-20', 'O263');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR253', '3', 'Nothing special, but decent.', '1-Jan-22', 'O264');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR254', '2', 'A bit bland.', '22-Jan-21', 'O265');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR255', '3', 'Average taste.', '3-Feb-26', 'O266');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR256', '1', 'Would not order again.', '2-Feb-24', 'O267');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR257', '3', 'Average taste.', '8-Feb-24', 'O268');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR258', '4', 'Really good food.', '30-Sep-23', 'O269');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR259', '2', 'Not exactly what I expected.', '11-Dec-21', 'O270');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR260', '3', 'It was okay.', '17-Oct-21', 'O271');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR261', '3', 'It was okay.', '26-Sep-24', 'O273');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR262', '5', 'Perfect as always!', '31-Mar-22', 'O274');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR263', '3', 'Average taste.', '20-Apr-22', 'O275');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR264', '5', 'Hot, fresh, and on time!', '3-Nov-25', 'O276');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR265', '1', 'Would not order again.', '26-May-21', 'O277');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR266', '5', 'Perfect as always!', '21-Dec-22', 'O278');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR267', '2', 'Food arrived slightly cold.', '15-Feb-22', 'O279');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR268', '3', 'Average taste.', '10-Apr-21', 'O280');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR269', '1', 'Food was completely ruined.', '2-Aug-22', 'O281');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR270', '4', 'Enjoyed the meal.', '29-Nov-24', 'O282');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR271', '1', 'Would not order again.', '30-Mar-23', 'O283');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR272', '1', 'Terrible experience.', '1-Oct-23', 'O284');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR273', '1', 'Would not order again.', '29-Dec-20', 'O286');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR274', '4', 'Really good food.', '4-Oct-20', 'O287');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR275', '5', 'Hot, fresh, and on time!', '28-Dec-22', 'O288');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR276', '1', 'Would not order again.', '18-Mar-23', 'O289');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR277', '4', 'Really good food.', '6-Apr-22', 'O290');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR278', '5', 'Absolutely delicious!', '17-Apr-20', 'O291');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR279', '4', 'Enjoyed the meal.', '7-Jun-20', 'O292');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR280', '3', 'Average taste.', '6-Dec-21', 'O294');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR281', '5', 'Perfect as always!', '28-Oct-22', 'O295');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR282', '5', 'Hot, fresh, and on time!', '11-Jan-23', 'O296');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR283', '1', 'Terrible experience.', '10-Jul-22', 'O297');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR284', '5', 'Hot, fresh, and on time!', '20-Aug-23', 'O298');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR285', '5', 'Hot, fresh, and on time!', '8-Aug-20', 'O299');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR286', '5', 'Perfect as always!', '9-Mar-20', 'O300');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR287', '5', 'Absolutely delicious!', '26-Nov-23', 'O301');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR288', '4', 'Enjoyed the meal.', '8-Jan-23', 'O302');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR289', '3', 'Nothing special, but decent.', '12-Mar-21', 'O303');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR290', '4', 'Enjoyed the meal.', '7-Aug-24', 'O305');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR291', '1', 'Terrible experience.', '22-Jan-26', 'O306');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR292', '2', 'Food arrived slightly cold.', '3-Jan-26', 'O307');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR293', '2', 'Food arrived slightly cold.', '5-Jul-23', 'O308');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR294', '2', 'Food arrived slightly cold.', '2-Aug-20', 'O309');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR295', '4', 'Good portion sizes.', '3-Apr-24', 'O310');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR296', '4', 'Enjoyed the meal.', '24-Jan-23', 'O311');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR297', '3', 'Nothing special, but decent.', '11-Feb-22', 'O312');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR298', '5', 'Absolutely delicious!', '2-Dec-23', 'O313');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR299', '1', 'Would not order again.', '30-Jul-21', 'O314');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR300', '5', 'Absolutely delicious!', '20-Apr-21', 'O315');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR301', '1', 'Terrible experience.', '21-Sep-25', 'O316');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR302', '3', 'Nothing special, but decent.', '12-Feb-22', 'O317');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR303', '2', 'A bit bland.', '25-Jul-21', 'O318');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR304', '1', 'Food was completely ruined.', '4-Sep-23', 'O319');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR305', '4', 'Enjoyed the meal.', '15-Feb-21', 'O320');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR306', '2', 'A bit bland.', '29-Dec-20', 'O321');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR307', '5', 'Hot, fresh, and on time!', '3-Jun-23', 'O322');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR308', '3', 'Nothing special, but decent.', '18-Sep-21', 'O323');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR309', '1', 'Would not order again.', '25-Dec-24', 'O324');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR310', '2', 'A bit bland.', '20-Jan-23', 'O325');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR311', '2', 'A bit bland.', '20-Aug-24', 'O326');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR312', '4', 'Good portion sizes.', '26-Aug-20', 'O327');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR313', '3', 'It was okay.', '28-Nov-25', 'O328');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR314', '3', 'Average taste.', '12-Feb-21', 'O329');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR315', '2', 'Not exactly what I expected.', '11-Feb-22', 'O330');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR316', '5', 'Hot, fresh, and on time!', '15-Feb-20', 'O331');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR317', '2', 'A bit bland.', '20-Sep-24', 'O333');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR318', '2', 'Not exactly what I expected.', '17-Nov-23', 'O334');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR319', '4', 'Good portion sizes.', '10-Sep-20', 'O335');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR320', '4', 'Enjoyed the meal.', '5-Oct-25', 'O336');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR321', '1', 'Would not order again.', '2-Oct-21', 'O337');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR322', '3', 'It was okay.', '12-Oct-22', 'O338');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR323', '2', 'Food arrived slightly cold.', '20-Apr-22', 'O339');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR324', '1', 'Would not order again.', '29-Aug-22', 'O340');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR325', '5', 'Perfect as always!', '22-Nov-23', 'O341');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR326', '1', 'Terrible experience.', '2-Nov-24', 'O342');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR327', '5', 'Absolutely delicious!', '5-Aug-22', 'O343');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR328', '4', 'Really good food.', '24-Jul-23', 'O344');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR329', '4', 'Good portion sizes.', '8-Jun-22', 'O346');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR330', '4', 'Enjoyed the meal.', '15-Oct-21', 'O347');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR331', '5', 'Hot, fresh, and on time!', '14-Mar-25', 'O348');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR332', '2', 'A bit bland.', '11-Nov-20', 'O349');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR333', '1', 'Terrible experience.', '6-Nov-23', 'O350');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR334', '3', 'Nothing special, but decent.', '23-Dec-23', 'O351');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR335', '3', 'It was okay.', '6-Jun-25', 'O352');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR336', '5', 'Absolutely delicious!', '4-Aug-25', 'O353');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR337', '3', 'It was okay.', '23-Apr-21', 'O354');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR338', '5', 'Absolutely delicious!', '1-Sep-22', 'O355');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR339', '4', 'Good portion sizes.', '21-Feb-24', 'O356');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR340', '2', 'Not exactly what I expected.', '1-Oct-25', 'O357');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR341', '3', 'Average taste.', '14-Jun-21', 'O358');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR342', '4', 'Good portion sizes.', '15-May-21', 'O359');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR343', '4', 'Good portion sizes.', '9-Apr-23', 'O360');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR344', '5', 'Perfect as always!', '21-May-23', 'O361');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR345', '1', 'Would not order again.', '5-Jun-20', 'O362');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR346', '1', 'Terrible experience.', '17-Feb-26', 'O363');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR347', '4', 'Good portion sizes.', '17-Dec-22', 'O364');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR348', '4', 'Good portion sizes.', '15-Sep-22', 'O366');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR349', '5', 'Absolutely delicious!', '17-Oct-21', 'O368');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR350', '1', 'Would not order again.', '14-May-21', 'O369');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR351', '2', 'Food arrived slightly cold.', '5-Dec-22', 'O370');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR352', '5', 'Absolutely delicious!', '20-Jul-24', 'O371');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR353', '2', 'Not exactly what I expected.', '16-Sep-22', 'O372');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR354', '4', 'Good portion sizes.', '16-Apr-22', 'O373');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR355', '2', 'Food arrived slightly cold.', '17-Feb-20', 'O375');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR356', '4', 'Really good food.', '23-Jul-20', 'O377');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR357', '1', 'Food was completely ruined.', '1-Apr-21', 'O378');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR358', '5', 'Perfect as always!', '11-Aug-25', 'O379');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR359', '3', 'Average taste.', '10-Apr-22', 'O380');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR360', '5', 'Perfect as always!', '18-Nov-23', 'O381');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR361', '2', 'A bit bland.', '20-Feb-20', 'O382');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR362', '5', 'Perfect as always!', '9-Nov-25', 'O383');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR363', '1', 'Terrible experience.', '5-Sep-20', 'O384');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR364', '3', 'Average taste.', '14-Aug-20', 'O385');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR365', '3', 'Nothing special, but decent.', '17-Aug-22', 'O386');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR366', '2', 'A bit bland.', '7-Apr-20', 'O387');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR367', '4', 'Really good food.', '14-Jun-25', 'O388');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR368', '2', 'A bit bland.', '18-Oct-21', 'O389');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR369', '3', 'It was okay.', '8-Oct-20', 'O390');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR370', '4', 'Really good food.', '28-Nov-25', 'O391');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR371', '4', 'Good portion sizes.', '16-Feb-23', 'O392');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR372', '4', 'Enjoyed the meal.', '18-Apr-21', 'O393');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR373', '4', 'Enjoyed the meal.', '18-Aug-23', 'O394');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR374', '5', 'Hot, fresh, and on time!', '16-Oct-25', 'O395');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR375', '5', 'Perfect as always!', '27-Mar-24', 'O396');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR376', '5', 'Perfect as always!', '19-Mar-22', 'O397');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR377', '1', 'Would not order again.', '6-Feb-24', 'O398');
INSERT INTO FoodRating (food_rating_id, rating_score, "comment", rating_date, orderid) VALUES('FR378', '2', 'Not exactly what I expected.', '17-Apr-25', 'O400');