SET DEFINE OFF;

INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR001, 5, 'The KFJ chicken was super crispy and fresh!', DATE '2026-01-05', 'OR001');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR002, 4, 'Good Nasi Lemak, but the sambal was a bit too sweet.', DATE '2026-01-06', 'OR002');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR003, 5, 'Haidilao never disappoints. Premium pork belly was 10/10.', DATE '2026-01-10', 'OR003');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR004, 3, 'Xiao Long Bao was cold when it arrived.', DATE '2026-01-15', 'OR005');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR005, 4, 'Sushi was fresh, worth the price.', DATE '2026-01-18', 'OR006');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR006, 5, 'KyoChon honey series is the best!', DATE '2026-01-20', 'OR007');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR007, 5, 'Loved the tomato soup base!', DATE '2026-01-22', 'OR008');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR008, 4, 'Burger was juicy but the wedges were slightly salty.', DATE '2026-01-25', 'OR009');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR009, 2, 'Burger was dry and very messy.', DATE '2026-01-28', 'OR010');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR010, 5, 'Amazing Korean Fried Chicken!', DATE '2026-02-01', 'OR011');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR011, 4, 'Rice was fluffy, chicken portion was generous.', DATE '2026-02-03', 'OR012');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR012, 3, 'Grilled chicken chop was a bit overcooked.', DATE '2026-02-05', 'OR013');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR013, 4, 'Fish and chips were good, tartar sauce was great.', DATE '2026-02-07', 'OR014');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR014, 5, 'Authentic Korean taste!', DATE '2026-02-12', 'OR016');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR015, 4, 'Best Nasi Lemak in town.', DATE '2026-02-14', 'OR017');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR016, 5, 'Beautiful mess burger is truly beautiful.', DATE '2026-02-16', 'OR018');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR017, 3, 'Juice jug was half ice.', DATE '2026-02-18', 'OR019');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR018, 5, 'High quality beef, very satisfied.', DATE '2026-02-20', 'OR020');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR019, 4, 'A Plus Burger indeed.', DATE '2026-02-22', 'OR021');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR020, 4, 'Nasi goreng was spicy and delicious!', DATE '2026-02-24', 'OR022');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR021, 5, 'Hot pot delivery was well-packed.', DATE '2026-02-26', 'OR023');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR022, 5, 'Perfectly cooked beef slices.', DATE '2026-02-28', 'OR024');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR023, 5, 'The Teriyaki Don was superb.', DATE '2026-01-07', 'OR031');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR024, 4, 'Fried rice was aromatic.', DATE '2026-01-08', 'OR032');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR025, 4, 'Sambal paru was quite spicy.', DATE '2026-01-09', 'OR033');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR026, 5, 'Family feast really fed the whole family!', DATE '2026-01-11', 'OR034');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR027, 4, 'Soup was rich and creamy.', DATE '2026-01-13', 'OR035');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR028, 5, 'Village Park is always a win.', DATE '2026-01-14', 'OR036');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR029, 2, 'Pai Tee was soggy.', DATE '2026-01-16', 'OR037');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR030, 5, 'Burger Lab is my favorite!', DATE '2026-01-17', 'OR038');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR031, 3, 'Dumplings were average.', DATE '2026-01-19', 'OR039');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR032, 4, 'Fruit rojak was refreshing.', DATE '2026-01-21', 'OR040');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR033, 4, 'Classic fried chicken taste.', DATE '2026-01-23', 'OR041');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR034, 5, 'Pork burger was surprisingly good.', DATE '2026-01-24', 'OR042');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR035, 4, 'Simple but tasty.', DATE '2026-01-26', 'OR043');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR036, 5, 'Amazing quality beef slices.', DATE '2026-01-27', 'OR044');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR037, 5, 'Soy garlic chicken is addicting.', DATE '2026-01-29', 'OR045');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR038, 3, 'Wontons were a bit small.', DATE '2026-01-30', 'OR046');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR039, 4, 'Roti was huge!', DATE '2026-01-31', 'OR047');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR040, 5, 'Twister wrap was fresh.', DATE '2026-02-02', 'OR048');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR041, 5, 'Spicy soup base was intense but good.', DATE '2026-02-04', 'OR049');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR042, 4, 'Chicken was moist and tasty.', DATE '2026-02-06', 'OR050');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR043, 3, 'Sambal sotong was very oily.', DATE '2026-02-08', 'OR051');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR044, 5, 'Burger Lab never fails.', DATE '2026-02-09', 'OR052');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR045, 4, 'Soup base was flavorful.', DATE '2026-02-11', 'OR053');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR046, 5, 'Mee Raja portion was huge.', DATE '2026-02-13', 'OR054');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR047, 5, 'Fat Elvis burger is a must try.', DATE '2026-02-15', 'OR055');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR048, 4, 'Nasi Lemak was authentic.', DATE '2026-02-17', 'OR056');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR049, 5, 'Love the beef slices.', DATE '2026-02-19', 'OR057');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR050, 4, 'Belly pork was great.', DATE '2026-02-21', 'OR058');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR051, 5, 'Grilled chicken chop was juicy.', DATE '2026-02-23', 'OR059');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR052, 4, 'Fried rice was good.', DATE '2026-02-25', 'OR060');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR053, 5, 'Best hot pot delivery service.', DATE '2026-02-27', 'OR061');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR054, 4, 'Fried honey chicken was sweet.', DATE '2026-03-01', 'OR062');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR055, 3, 'Popcorn chicken was dry.', DATE '2026-03-02', 'OR063');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR056, 5, 'Prawn paste was handmade and tasty.', DATE '2026-03-03', 'OR064');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR057, 4, 'Teriyaki don was filling.', DATE '2026-03-04', 'OR065');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR058, 4, 'Fried rice was okay.', DATE '2026-03-05', 'OR066');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR059, 3, 'Sambal paru was average.', DATE '2026-01-05', 'OR067');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR060, 5, 'Family feast was worth it.', DATE '2026-01-06', 'OR068');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR061, 4, 'Beef was tender.', DATE '2026-01-07', 'OR069');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR062, 5, 'Nasi lemak was great.', DATE '2026-01-08', 'OR070');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR063, 4, 'Steamed chicken was soft.', DATE '2026-01-09', 'OR071');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR064, 5, 'Burger mess was delicious.', DATE '2026-01-10', 'OR072');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR065, 5, 'Xiao Long Bao 10/10.', DATE '2026-01-11', 'OR073');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR066, 4, 'Rojak was sweet and spicy.', DATE '2026-01-12', 'OR074');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR067, 5, 'KFJ is always reliable.', DATE '2026-01-13', 'OR075');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR068, 4, 'Pork burger was okay.', DATE '2026-01-14', 'OR076');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR069, 5, 'Zinger burger was spicy!', DATE '2026-01-15', 'OR077');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR070, 4, 'Beef slices were plenty.', DATE '2026-01-16', 'OR078');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR071, 5, 'Best fried chicken ever.', DATE '2026-01-17', 'OR079');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR072, 4, 'Rice was fluffy.', DATE '2026-01-18', 'OR080');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR073, 5, 'Love the Nasi Lemak.', DATE '2026-01-19', 'OR081');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR074, 4, 'Twister was healthy.', DATE '2026-01-20', 'OR082');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR075, 4, 'Soup base was hot.', DATE '2026-01-21', 'OR083');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR076, 5, 'Honey chicken was crisp.', DATE '2026-01-22', 'OR084');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR077, 4, 'Daging rendang was tender.', DATE '2026-01-23', 'OR085');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR078, 5, 'Messy but good burger.', DATE '2026-01-24', 'OR086');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR079, 4, 'Hot pot was authentic.', DATE '2026-01-25', 'OR087');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR080, 5, 'Mee Raja portion for two!', DATE '2026-01-26', 'OR088');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR081, 4, 'The IPP beansprouts were crunchy and fresh.', DATE '2026-01-27', 'OR089');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR082, 3, 'Kopi was a bit too bitter today.', DATE '2026-01-28', 'OR090');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR083, 5, 'Best sliced beef I have had in a long time.', DATE '2026-01-29', 'OR091');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR084, 5, 'Enoki mushrooms were fresh and delicious.', DATE '2026-01-30', 'OR092');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR085, 4, 'The grilled chicken was juicy, but fries were cold.', DATE '2026-01-31', 'OR093');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR086, 4, 'Shrimp fried rice had plenty of shrimp!', DATE '2026-02-01', 'OR094');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR087, 5, 'Tomato soup base is a game changer.', DATE '2026-02-02', 'OR095');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR088, 5, 'Honey chicken series is absolute perfection.', DATE '2026-02-03', 'OR096');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR089, 4, 'Popcorn chicken was a bit dry but still tasty.', DATE '2026-02-04', 'OR097');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR090, 5, 'Handmade prawn paste was excellent.', DATE '2026-02-05', 'OR098');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR091, 4, 'Teriyaki don portion was just right.', DATE '2026-02-06', 'OR099');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR092, 5, 'Fried rice was very aromatic.', DATE '2026-02-07', 'OR100');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR093, 2, 'The ORer was cancelled but the refund process was slow.', DATE '2026-01-12', 'OR004');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR094, 3, 'Delivery was late, food was lukewarm.', DATE '2026-02-10', 'OR015');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR095, 4, 'Very filling meal, will ORer again.', DATE '2026-03-01', 'OR025');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR096, 5, 'Excellent service and great food.', DATE '2026-01-05', 'OR067');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR097, 4, 'Overall good experience.', DATE '2026-01-14', 'OR076');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR098, 5, 'Super deal indeed! Great value.', DATE '2026-01-20', 'OR082');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR099, 4, 'Tasty and fresh.', DATE '2026-01-26', 'OR088');
INSERT INTO FoodRating(food_rating_ID, rating_score, "comment", rating_date, orderID) VALUES(FR100, 3, 'Average quality, could be improved.', DATE '2026-02-04', 'OR097');

COMMIT;
