SET DEFINE OFF;
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY001', 'E-Wallet', 'Completed', 45.50, DATE '2026-01-05', 'OR001');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY002', 'Cash', 'Completed', 12.90, DATE '2026-01-06', 'OR002');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY003', 'Credit Card', 'Completed', 32.00, DATE '2026-01-10', 'OR003');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY004', 'Debit Card', 'Failed', 15.50, DATE '2026-01-12', 'OR004');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY005', 'E-Wallet', 'Completed', 55.20, DATE '2026-01-15', 'OR005');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY006', 'Credit Card', 'Completed', 22.10, DATE '2026-01-18', 'OR006');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY007', 'Debit Card', 'Completed', 18.00, DATE '2026-01-20', 'OR007');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY008', 'E-Wallet', 'Completed', 40.00, DATE '2026-01-22', 'OR008');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY009', 'Cash', 'Completed', 12.50, DATE '2026-01-25', 'OR009');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY010', 'Credit Card', 'Completed', 65.00, DATE '2026-01-28', 'OR010');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY011', 'E-Wallet', 'Completed', 29.90, DATE '2026-02-01', 'OR11');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY012', 'Cash', 'Completed', 14.50, DATE '2026-02-03', 'OR012');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY013', 'Debit Card', 'Completed', 33.40, DATE '2026-02-05', 'OR013');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY014', 'E-Wallet', 'Completed', 19.90, DATE '2026-02-07', 'OR014');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY015', 'Credit Card', 'Failed', 50.00, DATE '2026-02-10', 'OR015');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY016', 'Cash', 'Completed', 25.50, DATE '2026-02-12', 'OR016');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY017', 'Debit Card', 'Completed', 11.00, DATE '2026-02-14', 'OR017');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY018', 'E-Wallet', 'Completed', 42.80, DATE '2026-02-16', 'OR018');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY019', 'Cash', 'Completed', 15.00, DATE '2026-02-18', 'OR019');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY020', 'Credit Card', 'Completed', 38.90, DATE '2026-02-20', 'OR020');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY021', 'Debit Card', 'Completed', 22.50, DATE '2026-02-22', 'OR021');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY022', 'Cash', 'Completed', 14.00, DATE '2026-02-24', 'OR022');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY023', 'E-Wallet', 'Completed', 55.00, DATE '2026-02-26', 'OR023');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY024', 'Credit Card', 'Completed', 31.20, DATE '2026-02-28', 'OR024');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY025', 'Debit Card', 'Completed', 18.90, DATE '2026-03-01', 'OR025');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY026', 'Cash', 'Pending', 44.00, DATE '2026-03-02', 'OR026');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY027', 'E-Wallet', 'Pending', 12.00, DATE '2026-03-03', 'OR027');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY028', 'Debit Card', 'Pending', 26.50, DATE '2026-03-04', 'OR028');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY029', 'Credit Card', 'Pending', 19.90, DATE '2026-03-05', 'OR029');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY030', 'E-Wallet', 'Pending', 35.00, DATE '2026-03-05', 'OR030');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY031', 'Cash', 'Completed', 15.90, DATE '2026-01-07', 'OR031');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY032', 'Credit Card', 'Completed', 24.50, DATE '2026-01-08', 'OR032');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY033', 'Debit Card', 'Completed', 10.00, DATE '2026-01-09', 'OR033');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY034', 'E-Wallet', 'Completed', 55.00, DATE '2026-01-11', 'OR034');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY035', 'Credit Card', 'Completed', 33.20, DATE '2026-01-13', 'OR035');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY036', 'Debit Card', 'Completed', 12.00, DATE '2026-01-14', 'OR036');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY037', 'Cash', 'Refunded', 45.00, DATE '2026-01-16', 'OR037');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY038', 'E-Wallet', 'Completed', 22.80, DATE '2026-01-17', 'OR038');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY039', 'Credit Card', 'Completed', 18.50, DATE '2026-01-19', 'OR039');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY040', 'Debit Card', 'Completed', 30.00, DATE '2026-01-21', 'OR040');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY041', 'E-Wallet', 'Completed', 14.90, DATE '2026-01-23', 'OR041');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY042', 'Credit Card', 'Completed', 50.00, DATE '2026-01-24', 'OR042');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY043', 'Cash', 'Completed', 12.50, DATE '2026-01-26', 'OR043');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY044', 'Debit Card', 'Completed', 65.20, DATE '2026-01-27', 'OR044');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY045', 'E-Wallet', 'Completed', 29.90, DATE '2026-01-29', 'OR045');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY046', 'Cash', 'Completed', 14.50, DATE '2026-01-30', 'OR046');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY047', 'Credit Card', 'Completed', 33.40, DATE '2026-01-31', 'OR047');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY048', 'Debit Card', 'Completed', 19.90, DATE '2026-02-02', 'OR048');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY049', 'E-Wallet', 'Completed', 50.00, DATE '2026-02-04', 'OR049');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY050', 'Cash', 'Completed', 25.50, DATE '2026-02-06', 'OR050');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY051', 'Credit Card', 'Completed', 11.00, DATE '2026-02-08', 'OR051');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY052', 'Debit Card', 'Completed', 42.80, DATE '2026-02-09', 'OR052');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY053', 'E-Wallet', 'Completed', 15.00, DATE '2026-02-11', 'OR053');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY054', 'Cash', 'Completed', 38.90, DATE '2026-02-13', 'OR054');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY055', 'Debit Card', 'Completed', 22.50, DATE '2026-02-15', 'OR055');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY056', 'E-Wallet', 'Completed', 14.00, DATE '2026-02-17', 'OR056');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY057', 'Credit Card', 'Completed', 55.00, DATE '2026-02-19', 'OR057');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY058', 'Cash', 'Completed', 31.20, DATE '2026-02-21', 'OR058');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY059', 'Debit Card', 'Completed', 18.90, DATE '2026-02-23', 'OR059');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY060', 'E-Wallet', 'Completed', 44.00, DATE '2026-02-25', 'OR060');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY061', 'Cash', 'Completed', 12.00, DATE '2026-02-27', 'OR061');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY062', 'Debit Card', 'Completed', 26.50, DATE '2026-03-01', 'OR062');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY063', 'Credit Card', 'Completed', 19.90, DATE '2026-03-02', 'OR063');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY064', 'E-Wallet', 'Completed', 35.00, DATE '2026-03-03', 'OR064');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY065', 'Cash', 'Completed', 15.90, DATE '2026-03-04', 'OR065');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY066', 'Debit Card', 'Completed', 24.50, DATE '2026-03-05', 'OR066');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY067', 'Credit Card', 'Completed', 10.00, DATE '2026-01-05', 'OR067');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY068', 'E-Wallet', 'Completed', 55.00, DATE '2026-01-06', 'OR068');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY069', 'Cash', 'Completed', 33.20, DATE '2026-01-07', 'OR069');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY070', 'Debit Card', 'Completed', 12.00, DATE '2026-01-08', 'OR070');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY071', 'E-Wallet', 'Completed', 45.00, DATE '2026-01-09', 'OR071');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY072', 'Credit Card', 'Completed', 22.80, DATE '2026-01-10', 'OR072');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY073', 'Cash', 'Completed', 18.50, DATE '2026-01-11', 'OR073');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY074', 'Debit Card', 'Completed', 30.00, DATE '2026-01-12', 'OR074');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY075', 'E-Wallet', 'Completed', 14.90, DATE '2026-01-13', 'OR075');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY076', 'Credit Card', 'Completed', 50.00, DATE '2026-01-14', 'OR076');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY077', 'Cash', 'Completed', 12.50, DATE '2026-01-15', 'OR077');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY078', 'Debit Card', 'Completed', 65.20, DATE '2026-01-16', 'OR078');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY079', 'E-Wallet', 'Completed', 29.90, DATE '2026-01-17', 'OR079');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY080', 'Cash', 'Completed', 14.50, DATE '2026-01-18', 'OR080');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY081', 'Credit Card', 'Completed', 33.40, DATE '2026-01-19', 'OR081');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY082', 'Debit Card', 'Completed', 19.90, DATE '2026-01-20', 'OR082');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY083', 'E-Wallet', 'Completed', 50.00, DATE '2026-01-21', 'OR083');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY084', 'Cash', 'Completed', 25.50, DATE '2026-01-22', 'OR084');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY085', 'Debit Card', 'Completed', 11.00, DATE '2026-01-23', 'OR085');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY086', 'E-Wallet', 'Completed', 42.80, DATE '2026-01-24', 'OR086');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY087', 'Credit Card', 'Completed', 15.00, DATE '2026-01-25', 'OR087');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY088', 'Cash', 'Completed', 38.90, DATE '2026-01-26', 'OR088');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY089', 'Debit Card', 'Completed', 22.50, DATE '2026-01-27', 'OR089');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY090', 'E-Wallet', 'Completed', 14.00, DATE '2026-01-28', 'OR090');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY091', 'Credit Card', 'Completed', 55.00, DATE '2026-01-29', 'OR091');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY092', 'Cash', 'Completed', 31.20, DATE '2026-01-30', 'OR092');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY093', 'Debit Card', 'Completed', 18.90, DATE '2026-01-31', 'OR093');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY094', 'E-Wallet', 'Completed', 44.00, DATE '2026-02-01', 'OR094');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY095', 'Cash', 'Completed', 12.00, DATE '2026-02-02', 'OR095');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY096', 'Credit Card', 'Completed', 26.50, DATE '2026-02-03', 'OR096');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY097', 'Debit Card', 'Completed', 19.90, DATE '2026-02-04', 'OR097');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY098', 'E-Wallet', 'Completed', 35.00, DATE '2026-02-05', 'OR098');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY099', 'Cash', 'Completed', 15.90, DATE '2026-02-06', 'OR099');
INSERT INTO Payment (paymentID, payment_method, payment_status, payment_amount, payment_date, ORerID) VALUES ('PY100', 'Credit Card', 'Completed', 24.50, DATE '2026-02-07', 'OR100');

COMMIT;
